Fixed subcycling in implicit coupling (for regular simulations)
precice/calculix-adapter pull request #106
Opened 2022-09-25 12:11 UTC by boris-martin

(Depends on #105 )

Fixes https://github.com/precice/calculix-adapter/issues/9. Essentially, checkpointing stores more data than previously (not only positions, but velocities and a few more things), because those additional fields must be stored when going back from more than an increment (time step). So previous implementation worked only when there was one step per window.

Still WIP:

- [ ] Refactoring & cleaning
- [ ] Outputting once per time step instead of once per window (using the buffer from #105)
- [ ] Allow user-defined output frequency (once every N steps)
- [ ] Testing on more cases, including thermal cases (only perpendicular flap so far)
- [ ] Check for redundancy (I may have copied more data than necessary?)

2022-09-26 13:32 UTC, boris-martin commented
Turns out adapting the buffer code is trickier than anticipated. I'm undrafting and I suggest staying on the current partial fix: correct results, but with one output every N time window instead of every N steps, with N defaulting to 1.
This will limit the introduction of new bugs for now.

2022-11-16 08:18 UTC, KyleDavisSA approved these changes
Changes look good. All new variables are freed in the end.  However the perpendicular flap does not function correctly. 

- develop branch with equal time steps functions correctly, but breaks for subcycling.
- with this PR, subcycling and equal time steps do not crash, but the flap hardly moves.

2022-11-16 13:23 UTC, MakisH requested changes
I tried running the perpendicular flap, but it looks like we need to consider updates based for v2.20:

- With v2.19 and this PR, the tutorial was running normally
- With v2.20, it is running normally
- With v2.20 and this PR, the flap does not move

Please also check if it actually fixes the original issue ([example on how to reproduce it](https://github.com/precice/calculix-adapter/issues/9#issuecomment-1199067524)).

2022-11-16 13:39 UTC, KyleDavisSA commented
My suggestion would be to continue with the v2.20 release and continue to work on subcycling. Rather have the adapter working correctly when all time steps are equal.

2022-11-16 16:23 UTC, MakisH commented
> > I tried running the perpendicular flap, but it looks like we need to consider updates based for v2.20:
> > ```
> > * With v2.19 and this PR, the tutorial was running normally
> > 
> > * With v2.20, it is running normally
> > 
> > * With v2.20 and this PR, the flap does not move
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please also check if it actually fixes the original issue ([example on how to reproduce it](https://github.com/precice/calculix-adapter/issues/9#issuecomment-1199067524)).
> 
> How did you build "This + 2.20 ?" Since this PR involves quite some modifications of the main file I planned to do it by hand

I checked out the `v2.20` branch and I merged this branch, which did not lead to any conflicts. I guess we do need to update things, but let's make that a bugfix release, then. There is no regression.

2025-07-18 07:16 UTC, MakisH commented
This now needs to be rebased on the latest state of the adapter, which has two version changes:

- CalculiX v2.19 -> v2.20
- preCICE v2 -> v3

Since the changes in this PR are relatively few, I suggest applying the ideas from this PR directly in the latest state of the code.

Since @boris-martin is not working on this anymore, I am closing this. If anyone wants to pick this up, start a new PR from develop, apply the same ideas, and add @boris-martin as co-author.

2025-07-18 07:16 UTC, closed without merging